id = "rfc"
name = "Slash RFC"
description = "An example extension showcasing slash commands."
version = "0.1.0"
schema_version = 1
authors = ["Zed Industries <hi@zed.dev>"]
repository = "https://github.com/zed-industries/zed"

[slash_commands.rfc]
description = "Inserts the text of RFC"
requires_argument = true
