id = "rfc"
name = "RFC: Request for Comments"
description = "Slash command for IETF RFCs: e.g. /rfc 3339"
version = "0.1.0"
schema_version = 1
authors = ["Peter Tripp <notpeter@notpeter.net>"]
repository = "https://github.com/notpeter/rfc-zed"

[slash_commands.rfc]
description = "Inserts the text of RFC"
requires_argument = true
